In [1]:
import pandas as pd

In [2]:
import altair as alt

In [3]:
my_list = [1,3,5,7,9,11,99,999, 9999]

In [4]:
my_series = pd.Series(my_list)

In [5]:
my_series.sum()

11133

In [6]:
my_series.max()

9999

In [7]:
my_series.min()

1

In [8]:
my_series.mean()

1237.0

In [9]:
my_series.median()

9.0

In [10]:
my_series.std()

3301.82843285353

In [11]:
my_series.describe()

count       9.000000
mean     1237.000000
std      3301.828433
min         1.000000
25%         5.000000
50%         9.000000
75%        99.000000
max      9999.000000
dtype: float64

In [12]:
committee_list = pd.read_csv("/Users/motes/python/pyNotebook/committees.csv")

In [13]:
committee_list.head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name,committee_position
0,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,382,1374469,YES ON PROPOSITION 51 - CALIFORNIANS FOR QUALI...,SUPPORT
1,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,383,1220380,COMMUNITY COLLEGE FACILITY COALITION ISSUES CO...,SUPPORT
2,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,384,1282321,TORLAKSON'S INVEST IN CALIFORNIA A BALLOT MEAS...,SUPPORT
3,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,385,1382843,CALIFORNIA TAXPAYERS AND EDUCATORS OPPOSED TO ...,OPPOSE
4,ocd-contest/85990193-9d6f-4600-b8e7-bf1317841d82,1362198,71,PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...,386,1362973,YES ON PROPOSITION 52 - A COALITION OF CALIFOR...,SUPPORT

In [14]:
committee_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ocd_prop_id             102 non-null    object
 1   calaccess_prop_id       102 non-null    int64
 2   ccdc_prop_id            102 non-null    int64
 3   prop_name               102 non-null    object
 4   ccdc_committee_id       102 non-null    int64
 5   calaccess_committee_id  102 non-null    int64
 6   committee_name          102 non-null    object
 7   committee_position      102 non-null    object
dtypes: int64(4), object(4)
memory usage: 6.5+ KB

In [15]:
contrib_list = pd.read_csv("/Users/motes/python/pyNotebook/contributions.csv")

In [16]:
contrib_list.head()

,calaccess_committee_id,committee_name,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
0,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-09-18,BERGMAN,GRETCHEN,SPRING VALLEY,CA,91978,A NEW PATH,EXECUTIVE DIRECTOR,False,84.0
1,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-09-18,KAHLE,MYRNA,SAN DIEGO,CA,92109,NATIONAL SCHOOL DISTRICT,TEACHER,False,35.0
2,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-07-15,MCDEVITT,LEO,ESCONDIDO,CA,92025,LIFE IONIZERS,SEO/CONTENT MANAGER,False,198.0
3,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-08-10,WARREN-SAMARIPA,STEPHANIE,SAN DIEGO,CA,92116,STEPHANIE WARREN SAMARIPA,ENTREPRENEUR,False,-50.0
4,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-07-26,WARREN-SAMARIPA,STEPHANIE,SAN DIEGO,CA,92116,STEPHANIE WARREN SAMARIPA,ENTREPRENEUR,True,50.0

In [17]:
contrib_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56379 entries, 0 to 56378
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   calaccess_committee_id        56379 non-null  int64
 1   committee_name                56379 non-null  object
 2   calaccess_filing_id           56379 non-null  int64
 3   date_received                 56379 non-null  object
 4   contributor_lastname          56375 non-null  object
 5   contributor_firstname         53411 non-null  object
 6   contributor_city              56369 non-null  object
 7   contributor_state             56363 non-null  object
 8   contributor_zip               56366 non-null  object
 9   contributor_employer          48572 non-null  object
 10  contributor_occupation        53273 non-null  object
 11  contributor_is_self_employed  56379 non-null  bool
 12  amount                        56379 non-null  float64
dtypes: bool(1), float64(1), int64(2), object(9)
memory usage: 5.2+ MB

In [18]:
committee_list.prop_name

0      PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...
1      PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...
2      PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...
3      PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...
4      PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...
                             ...
97     PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...
98     PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...
99     PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...
100    PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...
101    PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...
Name: prop_name, Length: 102, dtype: object

In [19]:
committee_list.prop_name.value_counts()

PROPOSITION 057 - CRIMINAL SENTENCES. JUVENILE CRIMINAL PROCEEDINGS AND SENTENCING. INITIATIVE CONSTITUTIONAL AMENDMENT AND STATUTE.                           13
PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTHCARE, TOBACCO USE PREVENTION, RESEARCH, AND LAW ENFORCEMENT. INITIATIVE CONSTITUTIONAL AMENDMENT AND STATUTE.    12
PROPOSITION 064- MARIJUANA LEGALIZATION. INITIATIVE STATUTE.                                                                                                   11
PROPOSITION 066- DEATH PENALTY. PROCEDURES. INITIATIVE STATUTE.                                                                                                 9
PROPOSITION 055 - TAX EXTENSION TO FUND EDUCATION AND HEALTHCARE. INITIATIVE CONSTITUTIONAL AMENDMENT.                                                          8
PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON SINGLE-USE PLASTIC BAGS.                                                                                         7
PROPOSITION 062- DEATH PENALTY. INITIATIVE STATUTE.                                                                                                             7
PROPOSITION 059- SB 254 (CHAPTER 20, STATUTES OF 2016), ALLEN. CAMPAIGN FINANCE: VOTER INSTRUCTION                                                              6
PROPOSITION 058 - SB 1174 (CHAPTER 753, STATUTES OF 2014), LARA. ENGLISH LANGUAGE EDUCATION                                                                     4
PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-12 SCHOOL AND COMMUNITY COLLEGE FACILITIES. INITIATIVE STATUTORY AMENDMENT.                                       4
PROPOSITION 054 - LEGISLATURE. LEGISLATION AND PROCEEDINGS. INITIATIVE CONSTITUTIONAL AMENDMENT AND STATUTE.                                                    4
PROPOSITION 053 - REVENUE BONDS. STATEWIDE VOTER APPROVAL. INITIATIVE CONSTITUTIONAL AMENDMENT.                                                                 4
PROPOSITION 063- FIREARMS. AMMUNITION SALES. INTIATIVE STATUTE.                                                                                                 4
PROPOSITION 052 - STATE FEES ON HOSPITALS. FEDERAL MEDI-CAL MATCHING FUNDS. INITIATIVE STATUTORY AND CONSTITUTIONAL AMENDMENT.                                  3
PROPOSITION 061- STATE PRESCRIPTION DRUG PURCHASES. PRICING STANDARDS. INITIATIVE STATUTE.                                                                      3
PROPOSITION 060- ADULT FILMS. CONDOMS. HEALTH REQUIREMENTS. INITIATIVE STATUTE.                                                                                 2
PROPOSITION 065- CARRY-OUT BAGS. CHARGES. INITIATIVE STATUTE.                                                                                                   1
Name: prop_name, dtype: int64

In [20]:
my_prop = "PROPOSITION 064- MARIJUANA LEGALIZATION. INITIATIVE STATUTE."

In [21]:
my_committees = committee_list[committee_list.prop_name == my_prop]

In [22]:
my_committees.head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name,committee_position
74,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT
75,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,457,1382525,NEW APPROACH PAC (MPO),SUPPORT
76,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,458,1376077,"CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...",SUPPORT
77,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,459,1382568,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",OPPOSE
78,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,460,1371855,"MARIJUANA POLICY PROJECT OF CALIFORNIA, YES ON 64",SUPPORT

In [23]:
my_committees.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11 entries, 74 to 84
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ocd_prop_id             11 non-null     object
 1   calaccess_prop_id       11 non-null     int64
 2   ccdc_prop_id            11 non-null     int64
 3   prop_name               11 non-null     object
 4   ccdc_committee_id       11 non-null     int64
 5   calaccess_committee_id  11 non-null     int64
 6   committee_name          11 non-null     object
 7   committee_position      11 non-null     object
dtypes: int64(4), object(4)
memory usage: 792.0+ bytes

In [24]:
contrib_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56379 entries, 0 to 56378
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   calaccess_committee_id        56379 non-null  int64
 1   committee_name                56379 non-null  object
 2   calaccess_filing_id           56379 non-null  int64
 3   date_received                 56379 non-null  object
 4   contributor_lastname          56375 non-null  object
 5   contributor_firstname         53411 non-null  object
 6   contributor_city              56369 non-null  object
 7   contributor_state             56363 non-null  object
 8   contributor_zip               56366 non-null  object
 9   contributor_employer          48572 non-null  object
 10  contributor_occupation        53273 non-null  object
 11  contributor_is_self_employed  56379 non-null  bool
 12  amount                        56379 non-null  float64
dtypes: bool(1), float64(1), int64(2), object(9)
memory usage: 5.2+ MB

In [25]:
merged = pd.merge(my_committees, contrib_list, on="calaccess_committee_id")

In [26]:
merged.head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
0,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-02-04,BRADEN QUIGLEY,LAURA,SACRAMENTO,CA,95825,LBQ STRATEGIES,CONSULTANT,False,100.0
1,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-01-05,"CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...",NaN,IRVINE,CA,92618,NaN,NaN,False,250000.0
2,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-01-29,"CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...",NaN,IRVINE,CA,92618,NaN,NaN,False,250000.0
3,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-03-28,"CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...",NaN,IRVINE,CA,92618,NaN,NaN,False,250000.0
4,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-01-05,DRUG POLICY ACTION,NaN,NEW YORK,NY,10001,NaN,NaN,False,250000.0

In [27]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 860 entries, 0 to 859
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ocd_prop_id                   860 non-null    object
 1   calaccess_prop_id             860 non-null    int64
 2   ccdc_prop_id                  860 non-null    int64
 3   prop_name                     860 non-null    object
 4   ccdc_committee_id             860 non-null    int64
 5   calaccess_committee_id        860 non-null    int64
 6   committee_name_x              860 non-null    object
 7   committee_position            860 non-null    object
 8   committee_name_y              860 non-null    object
 9   calaccess_filing_id           860 non-null    int64
 10  date_received                 860 non-null    object
 11  contributor_lastname          860 non-null    object
 12  contributor_firstname         750 non-null    object
 13  contributor_city              860 non-null    object
 14  contributor_state             860 non-null    object
 15  contributor_zip               860 non-null    object
 16  contributor_employer          657 non-null    object
 17  contributor_occupation        742 non-null    object
 18  contributor_is_self_employed  860 non-null    bool
 19  amount                        860 non-null    float64
dtypes: bool(1), float64(1), int64(5), object(13)
memory usage: 135.2+ KB

In [28]:
merged.amount.sum()

35177017.64

In [29]:
merged.committee_position

0      SUPPORT
1      SUPPORT
2      SUPPORT
3      SUPPORT
4      SUPPORT
        ...
855    SUPPORT
856     OPPOSE
857     OPPOSE
858     OPPOSE
859     OPPOSE
Name: committee_position, Length: 860, dtype: object

In [30]:
merged.committee_position.value_counts()

SUPPORT    762
OPPOSE      98
Name: committee_position, dtype: int64

In [31]:
support = merged[merged.committee_position == 'SUPPORT']

In [32]:
oppose = merged[merged.committee_position == 'OPPOSE']

In [33]:
support.amount.sum()

32675806.0

In [34]:
oppose.amount.sum()

2501211.64

In [35]:
support.amount.sum()/merged.amount.sum()*100

92.88964270479867

In [36]:
merged.sort_values("amount", ascending=False).head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
142,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2083528,2016-09-15,PARKER AND AFFILIATED ENTITIES,SEAN,PALO ALTO,CA,94301,NaN,NaN,False,4000000.0
79,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2083528,2016-09-15,"DRUG POLICY ACTION - NON PROFIT 501C4, YES ON ...",NaN,SACRAMENTO,CA,95815,NaN,NaN,False,2000000.0
846,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,464,1385506,"DRUG POLICY ACTION - NON PROFIT 501C4, YES ON ...",SUPPORT,"DRUG POLICY ACTION - NON PROFIT 501C4, YES ON ...",2083608,2016-09-15,FUND FOR POLICY REFORM (NONPROFIT 501 (C)(4)),NaN,NEW YORK,NY,10019,NaN,NaN,False,1970000.0
851,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,465,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),SUPPORT,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),2082414,2016-09-15,FUND FOR POLICY REFORM,NaN,WILMINGTON,DE,19809,NaN,NaN,False,1970000.0
852,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,465,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),SUPPORT,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),2096507,2016-09-27,FUND FOR POLICY REFORM,NaN,WILMINGTON,DE,19809,NaN,NaN,False,1403000.0

In [37]:
support.sort_values('amount', ascending=False).head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
142,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2083528,2016-09-15,PARKER AND AFFILIATED ENTITIES,SEAN,PALO ALTO,CA,94301,NaN,NaN,False,4000000.0
79,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2083528,2016-09-15,"DRUG POLICY ACTION - NON PROFIT 501C4, YES ON ...",NaN,SACRAMENTO,CA,95815,NaN,NaN,False,2000000.0
851,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,465,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),SUPPORT,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),2082414,2016-09-15,FUND FOR POLICY REFORM,NaN,WILMINGTON,DE,19809,NaN,NaN,False,1970000.0
846,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,464,1385506,"DRUG POLICY ACTION - NON PROFIT 501C4, YES ON ...",SUPPORT,"DRUG POLICY ACTION - NON PROFIT 501C4, YES ON ...",2083608,2016-09-15,FUND FOR POLICY REFORM (NONPROFIT 501 (C)(4)),NaN,NEW YORK,NY,10019,NaN,NaN,False,1970000.0
852,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,465,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),SUPPORT,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),2096507,2016-09-27,FUND FOR POLICY REFORM,NaN,WILMINGTON,DE,19809,NaN,NaN,False,1403000.0

In [38]:
oppose.sort_values('amount', ascending=False).head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
839,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,463,1387789,"SAM ACTION, INC., A COMMITTEE AGAINST PROPOSIT...",OPPOSE,"SAM ACTION, INC., A COMMITTEE AGAINST PROPOSIT...",2083142,2016-07-20,SCHAUER,JULIE,OAKS,PA,19456,NaN,RETIRED,False,1000000.0
312,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,459,1382568,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",OPPOSE,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",2098048,2016-09-27,"SAM ACTION, INC.",NaN,ALEXANDRIA,VA,22314,NaN,NaN,False,400000.0
310,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,459,1382568,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",OPPOSE,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",2083071,2016-09-15,"SAM ACTION, INC.",NaN,ALEXANDRIA,VA,22314,NaN,NaN,False,225000.0
308,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,459,1382568,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",OPPOSE,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",2083071,2016-09-12,"SAM ACTION, INC.",NaN,ALEXANDRIA,VA,22314,NaN,NaN,False,200000.0
840,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,463,1387789,"SAM ACTION, INC., A COMMITTEE AGAINST PROPOSIT...",OPPOSE,"SAM ACTION, INC., A COMMITTEE AGAINST PROPOSIT...",2083142,2016-07-25,SCHAUER,JULIE,OAKS,CA,19456,NaN,RETIRED,False,150000.0

In [39]:
merged.groupby("contributor_state").amount.sum().reset_index()

   contributor_state       amount
0                 AB         0.00
1                 AL       100.00
2                 AZ       500.00
3                 BC         0.00
4                 CA  17491193.00
5                 CO     39300.00
6                 CT       100.00
7                 DC   2618600.00
8                 DE   6140100.00
9                 FL   1250850.00
10                GA       100.00
11                ID      1000.00
12                IL      7000.00
13                LA       100.00
14                MA       600.00
15                MD      2971.00
16                MI       400.00
17                MO       550.00
18                NC       200.00
19                NV      1800.00
20                NY   5446985.00
21                OH      2950.00
22                OK       200.00
23                OR      1400.00
24                PA   1215475.00
25                RI      6700.00
26                TX      1800.00
27                VA    895243.64
28                WA     50800.00

In [40]:
merged[merged.contributor_state == 'AL']

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
368,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,460,1371855,"MARIJUANA POLICY PROJECT OF CALIFORNIA, YES ON 64",SUPPORT,"MARIJUANA POLICY PROJECT OF CALIFORNIA, YES ON 64",2060277,2016-06-17,WHIDDON,LES,NEWVILLE,AL,363534054,SAINTS INDUSTRIES,OWNER,False,100.0

In [41]:
merged[merged.contributor_state == 'GA']

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
549,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,461,1343793,"CALIFORNIANS FOR RESPONSIBLE MARIJUANA REFORM,...",SUPPORT,"CALIFORNIANS FOR RESPONSIBLE MARIJUANA REFORM,...",2063970,2016-06-19,KAISER,DAVID,ATLANTA,GA,30338,FLIPSIDE CAPITAL,MANAGING DIRECTOR,False,100.0

In [42]:
merged.groupby("contributor_state").amount.sum().reset_index().sort_values("amount", ascending = False)

   contributor_state       amount
4                 CA  17491193.00
8                 DE   6140100.00
20                NY   5446985.00
7                 DC   2618600.00
9                 FL   1250850.00
24                PA   1215475.00
27                VA    895243.64
28                WA     50800.00
5                 CO     39300.00
12                IL      7000.00
25                RI      6700.00
15                MD      2971.00
21                OH      2950.00
26                TX      1800.00
19                NV      1800.00
23                OR      1400.00
11                ID      1000.00
14                MA       600.00
17                MO       550.00
2                 AZ       500.00
16                MI       400.00
18                NC       200.00
22                OK       200.00
1                 AL       100.00
13                LA       100.00
10                GA       100.00
6                 CT       100.00
3                 BC         0.00
0                 AB         0.00

In [43]:
merged.groupby(["contributor_firstname", "contributor_lastname", "committee_position"]).amount.sum().reset_index().sort_values("amount", ascending = False)

,contributor_firstname,contributor_lastname,committee_position,amount
483,SEAN,PARKER AND AFFILIATED ENTITIES,SUPPORT,7250000.0
482,SEAN,PARKER,SUPPORT,1500000.0
281,JULIE,SCHAUER,OPPOSE,1364000.0
108,DANIEL,LEWIS,SUPPORT,1250000.0
194,HENRY,VAN AMERINGEN,SUPPORT,1000000.0
...,...,...,...,...
430,RICH,GOLDBERG,SUPPORT,25.0
358,MARSTON,MEDLOCK,SUPPORT,0.0
497,STEPHANIE,WARREN-SAMARIPA,SUPPORT,0.0
16,AMIRGHASEM,SAMIMI-ARDESTAN,SUPPORT,0.0
136,DAVID,WOOD,SUPPORT,0.0

In [44]:
support.fillna("__Blank__").groupby(["contributor_firstname", "contributor_lastname", "committee_position"]).amount.sum().reset_index().sort_values("amount", ascending = False).head()

,contributor_firstname,contributor_lastname,committee_position,amount
444,SEAN,PARKER AND AFFILIATED ENTITIES,SUPPORT,7250000.0
526,__Blank__,FUND FOR POLICY REFORM,SUPPORT,6140000.0
527,__Blank__,FUND FOR POLICY REFORM (NONPROFIT 501 (C)(4)),SUPPORT,3940000.0
519,__Blank__,"DRUG POLICY ACTION - NON PROFIT 501C4, YES ON ...",SUPPORT,3000000.0
538,__Blank__,NEW APPROACH PAC (MPO),SUPPORT,2615000.0

In [45]:
oppose.fillna("__Blank__").groupby(["contributor_firstname", "contributor_lastname", "committee_position"]).amount.sum().reset_index().sort_values("amount", ascending = False).head()

,contributor_firstname,contributor_lastname,committee_position,amount
20,JULIE,SCHAUER,OPPOSE,1364000.0
66,__Blank__,"SAM ACTION, INC.",OPPOSE,889650.0
52,__Blank__,"CALIFORNIANS FOR JOBS, ASSEMBLYMEMBER JIM COOP...",OPPOSE,25000.0
51,__Blank__,CALIF. TEAMSTERS PUBLIC AFFAIRS COUNCIL ISSUES...,OPPOSE,25000.0
45,__Blank__,CALIF. ASSOC. OF HIGHWAY PATROLMEN,OPPOSE,25000.0

In [46]:
merged.fillna("==NULL==").sort_values("amount", ascending=False).head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
142,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2083528,2016-09-15,PARKER AND AFFILIATED ENTITIES,SEAN,PALO ALTO,CA,94301,==NULL==,==NULL==,False,4000000.0
79,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2083528,2016-09-15,"DRUG POLICY ACTION - NON PROFIT 501C4, YES ON ...",==NULL==,SACRAMENTO,CA,95815,==NULL==,==NULL==,False,2000000.0
846,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,464,1385506,"DRUG POLICY ACTION - NON PROFIT 501C4, YES ON ...",SUPPORT,"DRUG POLICY ACTION - NON PROFIT 501C4, YES ON ...",2083608,2016-09-15,FUND FOR POLICY REFORM (NONPROFIT 501 (C)(4)),==NULL==,NEW YORK,NY,10019,==NULL==,==NULL==,False,1970000.0
851,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,465,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),SUPPORT,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),2082414,2016-09-15,FUND FOR POLICY REFORM,==NULL==,WILMINGTON,DE,19809,==NULL==,==NULL==,False,1970000.0
852,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,465,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),SUPPORT,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),2096507,2016-09-27,FUND FOR POLICY REFORM,==NULL==,WILMINGTON,DE,19809,==NULL==,==NULL==,False,1403000.0

In [47]:
oppose.groupby(["contributor_employer"]).amount.sum().reset_index().sort_values("amount", ascending = False).head()

   contributor_employer  amount
17                   CS  6500.0
18                  CSI  5000.0
4     BOSTON SCIENTIFIC  1550.0
23                 NONE  1500.0
25              RETIRED  1371.0

In [48]:
support.groupby(["contributor_employer"]).amount.sum().reset_index().sort_values("amount", ascending = False).head()

          contributor_employer     amount
322     SEAN PARKER FOUNDATION  1250000.0
294                    RETIRED   502300.0
351  TAO CAPITAL PARTNERS, LLC   450000.0
350   TAO CAPITAL PARTNERS LLC   450000.0
361         THIEL CAPITAL, LLC   300000.0

In [49]:
merged.calaccess_committee_id.value_counts()

1343793    420
1381808    250
1382568     88
1371855     40
1386560     26
1382525      9
1385745      8
1385506      7
1387789      6
1390962      4
1376077      2
Name: calaccess_committee_id, dtype: int64

In [51]:
merged.calaccess_committee_id

0      1381808
1      1381808
2      1381808
3      1381808
4      1381808
        ...
855    1385745
856    1390962
857    1390962
858    1390962
859    1390962
Name: calaccess_committee_id, Length: 860, dtype: int64

In [70]:
top_supporters = support.fillna("==NULL==").groupby(["contributor_firstname", "contributor_lastname"]).amount.sum().reset_index().sort_values("amount", ascending=False).head(20)

In [71]:
top_supporters.head(10)

,contributor_firstname,contributor_lastname,amount
487,SEAN,PARKER AND AFFILIATED ENTITIES,7250000.0
19,==NULL==,FUND FOR POLICY REFORM,6140000.0
20,==NULL==,FUND FOR POLICY REFORM (NONPROFIT 501 (C)(4)),3940000.0
12,==NULL==,"DRUG POLICY ACTION - NON PROFIT 501C4, YES ON ...",3000000.0
31,==NULL==,NEW APPROACH PAC (MPO),2615000.0
486,SEAN,PARKER,1500000.0
145,DANIEL,LEWIS,1250000.0
223,HENRY,VAN AMERINGEN,1000000.0
11,==NULL==,DRUG POLICY ACTION,1000000.0
417,NICHOLAS,PRITZKER,900000.0

In [75]:
alt.Chart(top_supporters.head(10)).mark_bar().encode(
    x="amount",
    y="contributor_lastname"
)

alt.Chart(...)

In [78]:
top_supporters["contributor_fullname"] = top_supporters.contributor_firstname + " " + top_supporters.contributor_lastname

In [79]:
top_supporters.contributor_fullname

487                  SEAN PARKER AND AFFILIATED ENTITIES
19                       ==NULL== FUND FOR POLICY REFORM
20     ==NULL== FUND FOR POLICY REFORM (NONPROFIT 501...
12     ==NULL== DRUG POLICY ACTION - NON PROFIT 501C4...
31                       ==NULL== NEW APPROACH PAC (MPO)
486                                          SEAN PARKER
145                                         DANIEL LEWIS
223                                  HENRY VAN AMERINGEN
11                           ==NULL== DRUG POLICY ACTION
417                                    NICHOLAS PRITZKER
21     ==NULL== GHOST MANAGEMENT GROUP, LLC DBA WEEDMAPS
3      ==NULL== CALIFORNIANS FOR SENSIBLE REFORM, SPO...
14     ==NULL== DRUG POLICY ACTION - NON-PROFIT 501C4...
2      ==NULL== CALIFORNIANS FOR RESPONSIBLE MARIJUAN...
433                                          PETER THIEL
13        ==NULL== DRUG POLICY ACTION - NON-PROFIT 501C4
9                      ==NULL== DR BRONNER'S MAGIC SOAPS
464                                        ROGER JENKINS
65                                         ANGELA HOWARD
36                       ==NULL== PRIVATEER HOLDINGS INC
dtype: object

In [89]:
alt.Chart(top_supporters.head(10)).mark_bar().encode(
    x="amount",
    y=alt.Y("contributor_fullname", sort='-x')
).properties(title="Top Contributors to the Dope")

alt.Chart(...)

In [94]:
top_contributors = merged.fillna("").groupby(
    ["contributor_firstname", "contributor_lastname", "committee_position"]
).amount.sum().reset_index().sort_values("amount", ascending=False).head(50)

In [95]:
top_contributors["contributor_fullname"] = top_contributors["contributor_firstname"] + " " + top_contributors["contributor_lastname"]

In [97]:
alt.Chart(top_contributors.head(20)).mark_bar().encode(
    x="amount",
    y=alt.Y("contributor_fullname",sort="-x"),
    color="committee_position"
)

alt.Chart(...)

In [98]:
top_supporters.head(20).to_csv("top_supporters.csv")